defmodule Klix.Events.Event do
  use Klix.Schema

  @categories ~w(music sports conference workshop networking party festival exhibition comedy theater food_drink charity other)
  @statuses ~w(draft published cancelled completed)

  schema "events" do
    field :title, :string
    field :slug, :string
    field :description, :string
    field :category, :string
    field :location, :string
    field :latitude, :float
    field :longitude, :float
    field :start_datetime, :utc_datetime_usec
    field :end_datetime, :utc_datetime_usec
    field :banner_image_url, :string
    field :portrait_image_url, :string
    field :additional_images, {:array, :string}, default: []
    field :status, :string, default: "draft"
    field :published_at, :utc_datetime_usec
    field :settings, :map, default: %{}
    field :flagged_at, :utc_datetime_usec
    field :flag_reason, :string
    # Generated by Postgres for full-text search; never written or loaded.
    field :search_vector, :string, writable: :never, load_in_query: false

    # Filled in by queries that aggregate ticket type inventory.
    field :total_capacity, :integer, virtual: true, default: 0
    field :tickets_sold, :integer, virtual: true, default: 0
    field :tickets_available, :integer, virtual: true, default: 0
    field :min_price, :decimal, virtual: true

    belongs_to :organizer, Klix.Accounts.Organizer
    has_many :ticket_types, Klix.Events.TicketType

    timestamps()
  end

  def categories, do: @categories
  def statuses, do: @statuses

  @fields ~w(title description category location latitude longitude start_datetime end_datetime
             banner_image_url portrait_image_url additional_images settings)a

  def changeset(event, attrs) do
    event
    |> cast(attrs, @fields)
    |> validate_required([:title, :category, :location, :start_datetime, :end_datetime])
    |> validate_length(:title, min: 3, max: 200)
    |> validate_length(:location, max: 300)
    |> validate_length(:description, max: 50_000)
    |> validate_inclusion(:category, @categories)
    |> validate_number(:latitude, greater_than_or_equal_to: -90, less_than_or_equal_to: 90)
    |> validate_number(:longitude, greater_than_or_equal_to: -180, less_than_or_equal_to: 180)
    |> validate_chronology()
    |> put_slug()
    |> unique_constraint(:slug)
  end

  def status_changeset(event, status) do
    event
    |> change(status: status)
    |> validate_inclusion(:status, @statuses)
    |> then(fn cs ->
      if status == "published" and is_nil(event.published_at),
        do: put_change(cs, :published_at, DateTime.utc_now()),
        else: cs
    end)
  end

  defp validate_chronology(changeset) do
    starts = get_field(changeset, :start_datetime)
    ends = get_field(changeset, :end_datetime)

    if starts && ends && DateTime.compare(ends, starts) != :gt,
      do: add_error(changeset, :end_datetime, "must be after the start time"),
      else: changeset
  end

  # Slugs are generated once and never change, so shared links keep working.
  defp put_slug(%Ecto.Changeset{data: %{slug: nil}} = changeset) do
    case get_change(changeset, :title) do
      nil -> changeset
      title -> put_change(changeset, :slug, slug_base(title) <> "-" <> random_suffix())
    end
  end

  defp put_slug(changeset), do: changeset

  defp slug_base(title) do
    case slugify(title) do
      "" -> "event"
      base -> base
    end
  end

  def slugify(text) do
    text
    |> :unicode.characters_to_nfd_binary()
    |> String.replace(~r/[^\x00-\x7F]/u, "")
    |> String.downcase()
    |> String.replace(~r/[^a-z0-9]+/, "-")
    |> String.trim("-")
    |> String.slice(0, 60)
    |> String.trim("-")
  end

  defp random_suffix, do: :crypto.strong_rand_bytes(4) |> Base.encode32(case: :lower, padding: false)

  def published?(%__MODULE__{status: status}), do: status == "published"
end
